#! /bin/bash

# Create diskimage and install GRUB2
# requires root permissions
# Tested on Ubuntu with grub-install (GRUB) 2.04-1ubuntu26.8

mount_dir="diskimage_mnt"

sysroot=$1
srcdir=$2
limine=$3

echo "Sysroot: ${sysroot}"
echo "Config Source directory: ${srcdir}"
echo "Limine root: ${limine}"

# create some directories
mkdir -p ${mount_dir}

# create the empty disk image (40MB)
dd if=/dev/zero of=disk.img bs=8192 count=5120

# generate msdos partition table and
# ext2 partition starting on sector 2048
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk disk.img
  o # clear the in memory partition table
  n # new partition
  p # primary partition
  1 # partition number 1
    # default - start at beginning of disk 
    # default - use entire disk
  a # make the partition bootable
  p # print the in-memory partition table
  w # write the partition table
  q # and we're done
EOF

# create loopback block devices
sudo losetup /dev/loop99 disk.img -o 1048576

# format ext2 filesystem
sudo mkfs.ext2 /dev/loop99
sudo mount /dev/loop99 ${mount_dir}

# create directories and copy files to the image
mkdir -p ${sysroot}/boot
cp ${limine}/bin/limine.sys ${sysroot}/boot/limine.sys
cp ${srcdir}/limine.cfg ${sysroot}/boot/limine.cfg
sudo cp -R ${sysroot}/* ${mount_dir}

sync
sudo umount /dev/loop99
sudo losetup -d /dev/loop99

${limine}/bin/limine-install disk.img
